- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!!"
    - name: Get collection versions
      shell: ansible-galaxy collection list
      register: collection_list

    - name: Show collection versions
      debug:
        var: collection_list.stdout_lines
